openapi: 3.0.3
info:
  title: Sessy API
  description: |-
    This is an overview of everything you can view and change in your P1 meter via its API. You can use it to geek out on stats at home, or integrate into your home automation.
    Wouldn't it be cool to have Sessy's P1 meter talk to all kinds of home automation software out there? Enjoy!
  version: 1.0.0
tags:
  - name: P1 Meter
    description: A way to request power metrics and change settings
paths:
  /api/v1/p1/status:
    get:
      tags:
        - P1 Meter
      summary: Returns only the actual power and state metrics of the P1 meter
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/p1_status'
        '500':
          description: An error occurred (error message in response body)
  /api/v1/p1/details:
    get:
      tags:
        - P1 Meter
      summary: Returns power and state metrics of the P1 meter
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/p1_details'
        '500':
          description: An error occurred (error message in response body)
components:
  schemas:
    p1_status:
      required:
        - status
        - state
        - net_power_delivered
      type: object
      properties:
        status:
          type: string
          example: ok
        state:
          type: string
          example: P1_OK
          enum:
            - P1_NOT_CONNECTED
            - P1_DATAVALIDITY_ERR
            - P1_VERSION_ERR
            - P1_PARSE_ERR
            - P1_OK
        net_power_delivered:
          type: number
          example: 2.25
          description: Indicates the power consumption measured by the P1 meter
    p1_details:
      required:
        - status
        - state
        - total_power
        - power_consumed
        - power_produced
        - voltage_l1
        - voltage_l2
        - voltage_l3
      type: object
      properties:
        status:
          type: string
          example: ok
        state:
          type: string
          example: P1_OK
          enum:
            - P1_NOT_CONNECTED
            - P1_DATAVALIDITY_ERR
            - P1_VERSION_ERR
            - P1_PARSE_ERR
            - P1_OK
        total_power:
          type: number
          example: 2.25
          description: Indicates the net power measured by the P1 meter
        power_consumed:
          type: number
          example: 3
          description: Indicates the total power measured by the P1 meter going in to the electricity grid
        power_produced:
          type: number
          example: 0.75
          description: Indicates the total power measured by the P1 meter going in to the electricity grid
        voltage_l1:
          type: number
          example: 231
          description: Phase voltage measured by the p1 meter
        voltage_l2:
          type: number
          example: 232
          description: Phase voltage measured by the p1 meter
        voltage_l3:
          type: number
          example: 233
          description: Phase voltage measured by the p1 meter
